<h1>GC Perf Report</h1>

Generated: ```r.date ``` <br>
RunID : ```r.version ``` <br>



```{r, echo = FALSE, cache=FALSE}

source('R/constants.R')
source('R/utils.R')
source('R/functions.R')
source('R/plot_functions.R')
source('R/style.R')
library(xtable)
library(ggplot2)
suppressPackageStartupMessages(library(googleVis))
```



```{r2, echo = FALSE, cache=FALSE}



data.file <- "input.txt"
data.file <- "dataParOld.txt"
data.gc <- read.csv(data.file,sep=',', header=TRUE)
data.gc <- computeAllocationRate(data.gc)

```



<h4>Summary</h4>
```{r rgooglevis,results="asis", echo = FALSE}
df <-statsMain(data.gc)
dd <- as.data.frame(df)
tab1 <- gvisTable(dd)
print(tab1, "chart")
```

<h4>GC stats by type:</h4>
```{r xtable, results="asis", echo = FALSE}
df <-statsByGCType(data.gc)

dd <- as.data.frame(df)
tab1 <- gvisTable(dd)
print(tab1, "chart")
```




<h4>GC Timeline</h4>
```{r fig.width=15, fig.height=6, echo = FALSE}
plotGC2(data.gc)
```

<h4>Histogram</h4>
```{r fig.width=10, results="asis", fig.height=6, echo = FALSE}
histo2(data.gc)
```

<h4>OldGen Occupation</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
sizeoldPlot(data.gc)
```

<h4>YoungGen Occupation Size</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
sizeYoungPlot(data.gc)
```

<h4>Survivor Occupation</h4>
```{r fig.width=15, fig.height=6, echo = FALSE}
survPlot(data.gc)
```

<h4>Occupation Overview</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
occupation(data.gc)
```




<h4>Old TimeSeries</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
plotGCseriesOld(data.gc)
```

<h4>Young TimeSeries</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
plotGCseries_Young(data.gc)
```

<h4>Survivor TimeSeries</h4>

```{r fig.width=15, fig.height=6, echo = FALSE}
plotGCseries_Survivor(data.gc)
```

```{r fig.width=10,results="asis", fig.height=6, echo = FALSE}
#dd <- data.frame(v1=data.gc$timestamp,v2=data.gc$pause.time,v3=data.gc$pause.time)
keep <- c("timestamp", "pause.time","young.occ.start")
dd<-data.gc[keep]
colnames(dd) <- keep
A0 <- gvisMotionChart(dd, idvar='pause.time', timevar='timestamp')
print(A0, 'chart')


#A1 <- gvisAnnotatedTimeLine(data.gc, datevar="timestamp",
#                           numvar="pause.time", idvar="Device",
#                           titlevar="Title", annotationvar="Annotation",
#                           )
#print(A1, 'chart')
```